Repository SCADA-LTS/Scada-LTS, pull requests merged in 2019-05, with the labels that each got.

#845 Feature/#844 fix parsing binary values merge to safe develop mirror
  WebContent/WEB-INF/jsp/pointEdit/pointProperties.jsp
  src/br/org/scadabr/api/dao/MangoDaoImpl.java
  src/com/serotonin/mango/rt/dataImage/types/BinaryValue.java
  src/com/serotonin/mango/vo/DataPointVO.java
  src/com/serotonin/mango/web/dwr/BaseDwr.java
  src/com/serotonin/mango/web/dwr/EventHandlersDwr.java
  src/com/serotonin/mango/web/dwr/beans/ImportTask.java
Labels: review

#853 Feature/#713 fix the user permission system
  ScadaLTS-UI-1/package-lock.json
  WebContent/WEB-INF/jsp/users.jsp
  src/br/org/scadabr/db/dao/UsersProfileDao.java
  src/br/org/scadabr/vo/permission/Permission.java
  src/br/org/scadabr/vo/permission/ViewAccess.java
  src/br/org/scadabr/vo/permission/WatchListAccess.java
  src/com/serotonin/mango/web/dwr/EmportDwr.java
  src/com/serotonin/mango/web/dwr/UsersDwr.java
  src/com/serotonin/mango/web/dwr/ViewDwr.java
  src/com/serotonin/mango/web/mvc/controller/WatchListController.java
  src/org/scada_lts/dao/DataPointUserDAO.java
  src/org/scada_lts/mango/service/UserService.java
  src/org/scada_lts/mango/service/WatchListService.java
  src/org/scada_lts/web/mvc/api/ViewAPI.java
  src/org/scada_lts/web/mvc/api/WatchListAPI.java
Labels: new develop

#851 Feature/#850 fix for tab views when database is empty
  WebContent/WEB-INF/jsp/viewEdit.jsp
  WebContent/WEB-INF/jsp/views.jsp
  WebContent/resources/restApiBusinessObjectForDwrScriptSessionId.js
  WebContent/resources/splitPartsAndReturnUrl.js
  src/com/serotonin/mango/Common.java
  src/com/serotonin/mango/ScriptSession.java
  src/com/serotonin/mango/web/dwr/ViewDwr.java
  src/org/scada_lts/session/HttpSessionListenerImpl.java
  src/org/scada_lts/web/mvc/api/BusinessObjectForScriptSessionIdAPI.java
  src/org/scada_lts/web/mvc/controller/FinalValuesForControllers.java
  src/org/scada_lts/web/mvc/controller/ViewEditController.java
Labels: review

#849 Feature/#748 fixed parsing binary value
  WebContent/WEB-INF/jsp/pointEdit/pointProperties.jsp
  src/br/org/scadabr/api/dao/MangoDaoImpl.java
  src/com/serotonin/mango/rt/dataImage/types/BinaryValue.java
  src/com/serotonin/mango/vo/DataPointVO.java
  src/com/serotonin/mango/web/dwr/BaseDwr.java
  src/com/serotonin/mango/web/dwr/EventHandlersDwr.java
  src/com/serotonin/mango/web/dwr/beans/ImportTask.java
Labels: new develop, review

#852 #838 Changed shape of drawing chart for numerical points
  src/com/serotonin/mango/vo/report/ImageChartUtils.java
Labels: new develop

#872 Feature/#871 revert commits causing problems
  WebContent/WEB-INF/classes/log4j.xml
  WebContent/WEB-INF/classes/messages_de.properties
  WebContent/WEB-INF/classes/messages_en.properties
  WebContent/WEB-INF/classes/messages_es.properties
  WebContent/WEB-INF/classes/messages_fi.properties
  WebContent/WEB-INF/classes/messages_fr.properties
  WebContent/WEB-INF/classes/messages_lu.properties
  WebContent/WEB-INF/classes/messages_nl.properties
  WebContent/WEB-INF/classes/messages_pl.properties
  WebContent/WEB-INF/classes/messages_pt.properties
  WebContent/WEB-INF/classes/messages_ru.properties
  WebContent/WEB-INF/classes/messages_zh.properties
  WebContent/WEB-INF/jsp/viewEdit.jsp
  WebContent/WEB-INF/jsp/views.jsp
  WebContent/WEB-INF/lib/snmp4j-2.5.0.jar
  build.xml
  src/com/serotonin/mango/rt/RuntimeManager.java
  src/com/serotonin/mango/rt/dataSource/DataSourceRT.java
  src/com/serotonin/mango/rt/dataSource/snmp/SnmpDataSourceRT.java
  src/com/serotonin/mango/web/mvc/controller/ViewsController.java
  test/com/serotonin/mango/rt/dataSource/snmp/SnmpDataSourceRTTest.java
Labels: new develop

#847 New/develop
  .travis.yml
  README.md
  ScadaLTS-UI-1/package-lock.json
  WebContent/WEB-INF/classes/messages_de.properties
  WebContent/WEB-INF/classes/messages_en.properties
  WebContent/WEB-INF/classes/messages_es.properties
  WebContent/WEB-INF/classes/messages_fr.properties
  WebContent/WEB-INF/classes/messages_lu.properties
  WebContent/WEB-INF/classes/messages_nl.properties
  WebContent/WEB-INF/classes/messages_pl.properties
  WebContent/WEB-INF/classes/messages_pt.properties
  WebContent/WEB-INF/classes/messages_zh.properties
  WebContent/WEB-INF/jsp/dataPointDetails.jsp
  WebContent/WEB-INF/jsp/dataSourceEdit.jsp
  WebContent/WEB-INF/jsp/include/customEditor.jsp
  WebContent/WEB-INF/jsp/include/graphicRendererEditor.jsp
  WebContent/WEB-INF/jsp/include/staticEditor.jsp
  WebContent/WEB-INF/jsp/pointEdit/pointProperties.jsp
  WebContent/WEB-INF/jsp/systemSettings.jsp
  WebContent/WEB-INF/jsp/users.jsp
  WebContent/WEB-INF/jsp/viewEdit.jsp
  WebContent/WEB-INF/jsp/views.jsp
  WebContent/WEB-INF/lib/seroUtils.jar
  WebContent/WEB-INF/snippet/alarmList.jsp
  WebContent/WEB-INF/snippet/infoContent.jsp
  WebContent/WEB-INF/tags/comments.tag
  WebContent/WEB-INF/tags/lastComment.tag
  src/br/org/scadabr/api/dao/MangoDaoImpl.java
  src/br/org/scadabr/db/dao/UsersProfileDao.java
  src/br/org/scadabr/rt/scripting/context/DSCommandsScriptContextObject.java
  src/br/org/scadabr/view/component/AlarmListComponent.java
  src/br/org/scadabr/vo/permission/Permission.java
  src/br/org/scadabr/vo/permission/ViewAccess.java
  src/br/org/scadabr/vo/permission/WatchListAccess.java
  src/br/org/scadabr/vo/scripting/ContextualizedScriptVO.java
  src/com/serotonin/mango/rt/RuntimeManager.java
  src/com/serotonin/mango/rt/dataImage/types/BinaryValue.java
  src/com/serotonin/mango/rt/maint/DataPurge.java
  src/com/serotonin/mango/vo/DataPointVO.java
  src/com/serotonin/mango/vo/report/ImageChartUtils.java
  src/com/serotonin/mango/web/dwr/BaseDwr.java
  src/com/serotonin/mango/web/dwr/EmportDwr.java
  src/com/serotonin/mango/web/dwr/EventHandlersDwr.java
  src/com/serotonin/mango/web/dwr/SystemSettingsDwr.java
  src/com/serotonin/mango/web/dwr/UsersDwr.java
  src/com/serotonin/mango/web/dwr/ViewDwr.java
  src/com/serotonin/mango/web/dwr/beans/ImportTask.java
  src/com/serotonin/mango/web/mvc/controller/ViewsController.java
  src/com/serotonin/mango/web/mvc/controller/WatchListController.java
  src/org/scada_lts/dao/DataPointUserDAO.java
  src/org/scada_lts/dao/SystemSettingsDAO.java
  src/org/scada_lts/mango/service/UserService.java
  src/org/scada_lts/mango/service/WatchListService.java
  src/org/scada_lts/web/mvc/api/DataPointAPI.java
  src/org/scada_lts/web/mvc/api/ViewAPI.java
  src/org/scada_lts/web/mvc/api/WatchListAPI.java
  src/org/scada_lts/web/mvc/controller/ViewEditController.java
Labels: review

#855 #854 Fixed export events and export user comments on reports module
  src/com/serotonin/mango/vo/report/EventCsvStreamer.java
  src/com/serotonin/mango/web/servlet/ReportExportBase.java
  src/org/scada_lts/dao/event/EventDAO.java
  src/org/scada_lts/dao/report/ReportInstanceDAO.java
Labels: new develop

#874 #873 Fix Alarm list component and move component versioning from view…
  src/br/org/scadabr/view/component/AlarmListComponent.java
  src/com/serotonin/mango/view/View.java
Labels: new develop
